/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semonster2;

import java.util.Random;

public class App {
  final static Random random = new Random();
  final static int maxRandomNumber = 4;

  public String getGreeting() {
    return "こんにちは SEMonster";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    Monster m = new Monster(3, 5);
    System.out.print(m.toString());
    m.evolve();
    System.out.print(m.toString());

  }
}
